dataset_params:
  # root_dir: '/home/nas2_userF/dataset/Voxceleb2'
  root_dir: '/home/yoonseokim/face-vid2vid-pytorch/data/Voxceleb2'
  frame_shape: [256, 256, 3]
  id_sampling: True
  pairs_list: None
  augmentation_params:
    flip_param:
      horizontal_flip: True
      time_flip: True
    jitter_param:
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
      hue: 0.1

model_params:
  common_params:
    depth: 16
    num_kp: 15
    num_channels: 3
  af_extractor:
    block_expansion: 64
    res_block_features: 32
    num_down_blocks: 2
    num_res_blocks: 6
  kp_detector:
    block_expansion: 64
    max_features: 1024
    num_blocks: 5
    temperature: 0.1
    scale_factor: 1
    estimate_jacobian: False
  he_estimator:
    block_expansion: 64
    num_layers: [3, 3, 5, 2]
  generator:
    output_channels: 3
    block_expansion: 64
    source_channels: 32
    num_res_blocks: 6
    num_up_blocks: 2
    estimate_occlusion_map: True
    dense_motion:
      block_expansion: 64
      num_blocks: 5
      max_features: 1024
      compress_channels: 4
      scale_factor: 1
      kp_variance: 0.01
  discriminator:
    scales: [1]
    block_expansion: 32
    max_features: 512
    num_blocks: 4
    sn: True

train_params:
  num_epochs: 100
  num_repeats: 1
  keypoint_distance_threshold: 0.1
  keypoint_depth_target: 0.33
  epoch_milestones: [120,]
  lr_af_extractor: 2.0e-4
  lr_kp_detector: 2.0e-4
  lr_he_estimator: 2.0e-4
  lr_generator: 2.0e-4
  lr_discriminator: 2.0e-4
  pretrained_hopenet_dir: pretrained/hopenet.pkl
  batch_size: 1
  scales: [1, 0.5, 0.25, 0.125]
  checkpoint_freq: 10
  transform_params:
    sigma_affine: 0.05
    sigma_tps: 0.005
    points_tps: 5
  loss_weights:
    generator_gan: 1
    discriminator_gan: 1
    feature_matching: [10, 10, 10, 10]
    perceptual: [10, 10, 10, 10, 10]
    # face_perceptual: 10
    equivariance_keypoints: 10
    equivariance_jacobian: 0
    keypoint_prior: 10
    # head_pose: 20
    deformation_prior: 5

visualizer_params:
  kp_size: 3
  draw_border: True
  colormap: 'gist_rainbow'
