dataset_params:
  root_dir: data/vox
  frame_shape: [224, 224, 3]

model_params:
  common_params:
    depth: 16
    num_kp: 20
    num_channels: 3
  appearance_feature_extractor:
    block_expansion: 64
    res_block_features: 32
    num_down_blocks: 2
    num_res_blocks: 6
  canonical_keypoint_detector:
    block_expansion: 64
    max_features: 1024
    num_blocks: 5
    temperature: 0.1
    scale_factor: 1
    estimate_jacobian: True
  head_expression_estimator:
    block_expansion: 256
    num_bins: 66
    num_layers: [3, 3, 5, 2]
  occlusion_aware_generator:
    output_channels: 3
    block_expansion: 64
    source_channels: 32
    num_res_blocks: 6
    num_up_blocks: 2
    estimate_occlusion_map: True
    motion_field_estimator:
      block_expansion: 64
      num_blocks: 5
      max_features: 1024
      compress_channels: 4
      scale_factor: 1
      kp_variance: 0.01
  multi_scale_discriminator:
    scales: [1, 0.5]
    block_expansion: 64
    max_features: 512
    negative: 0.2
    num_blocks: 5

train_params:
  num_epochs: 100
  num_repeats: 75
  num_bins: 66
  keypoint_distance_threshold: 0.1
  keypoint_depth_target: 0.33
  epoch_milestones: [60, 90]
  lr_appearance_feature_extractor: 2.0e-4
  lr_canonical_keypoint_detector: 2.0e-4
  lr_head_expression_estimator: 2.0e-4
  lr_occlusion_aware_generator: 2.0e-4
  lr_multi_scale_discriminator: 2.0e-4
  pretrained_hopenet_dir: pretrained/hopenet.pkl
  batch_size: 40
  scales: [1, 0.5, 0.25, 0.125]
  checkpoint_freq: 10
  transform_params:
    sigma_affine: 0.05
    sigma_tps: 0.005
    points_tps: 5
  loss_weights:
    generator_gan: 1
    discriminator_gan: 1
    feature_matching: [10, 10, 10, 10]
    perceptual: [10, 10, 10, 10, 10]
    equivariance_keypoints: 20
    equivariance_jacobian: 20
    keypoint_prior: 10
    head_pose: 20
    deformaioin_prior: 5

visualizer_params:
  kp_size: 5
  draw_border: True
  colormap: 'gist_rainbow'
